coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_base: no
  require_head: yes
  require_changes: no
